# 端口配置
server:
  port: 8085

spring:

# jdbc配置
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456

# 热部署
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: resource/**, static/**, templates/**

# mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
